print("Hello, World!")
print("My name is Mariam")
print("MY surname is Dzadzua")
print("I'm 26 years old")
print("My favorite color is white")
print("I'm Goa's student")
print("I have a good teacher")
print("Students in Goa are very friendly")
print(2025)
print("Saturday")
print("We must study very well")
print("We have enough motivation to do exercises")
print("Just be kind, Life isn't so long")
print("Try a little harder to be a little better")
print("There are no elevators to success, you have to take the stairs")
print("A good friend is like a four-leaf clover - hard to find and lucky to have")
print("It does not matter how slowly you go as long as you do not stop")
print("Nothing will work unless you do")
print("The only bad workout is the one that didn't happen")
print("Reading is dreaming with eyes wide open")